export const galleryThemes = [
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    description: "Clean, dark theme with subtle accents",
    category: "minimal",
    featured: true,
    colors: {
      primary: "#8b5cf6",
      accent: "#6d28d9",
      background: "#0f172a",
      foreground: "#f8fafc",
      muted: "#334155",
      border: "#1e293b",
      linkBackground: "#1e293b",
      linkForeground: "#f8fafc",
      borderRadius: "0.5rem",
    },
  },
  {
    id: "vibrant-gradient",
    name: "Vibrant Gradient",
    description: "Bold, colorful theme with gradient accents",
    category: "vibrant",
    featured: true,
    colors: {
      primary: "#ec4899",
      accent: "#8b5cf6",
      background: "#18181b",
      foreground: "#ffffff",
      muted: "#3f3f46",
      border: "#27272a",
      linkBackground: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
      linkForeground: "#ffffff",
      borderRadius: "1rem",
    },
  },
  {
    id: "professional-blue",
    name: "Professional Blue",
    description: "Clean, professional theme with blue accents",
    category: "professional",
    featured: false,
    colors: {
      primary: "#0ea5e9",
      accent: "#0284c7",
      background: "#ffffff",
      foreground: "#0f172a",
      muted: "#94a3b8",
      border: "#e2e8f0",
      linkBackground: "#f1f5f9",
      linkForeground: "#0f172a",
      borderRadius: "0.375rem",
    },
  },
  {
    id: "nature-green",
    name: "Nature Green",
    description: "Earthy, calming theme with green tones",
    category: "minimal",
    featured: false,
    colors: {
      primary: "#10b981",
      accent: "#059669",
      background: "#f8fafc",
      foreground: "#1e293b",
      muted: "#94a3b8",
      border: "#e2e8f0",
      linkBackground: "#ecfdf5",
      linkForeground: "#064e3b",
      borderRadius: "0.75rem",
    },
  },
  {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    description: "Bold, futuristic theme with neon accents",
    category: "vibrant",
    featured: true,
    colors: {
      primary: "#06b6d4",
      accent: "#f472b6",
      background: "#0f172a",
      foreground: "#f8fafc",
      muted: "#334155",
      border: "#1e293b",
      linkBackground: "#0f172a",
      linkForeground: "#06b6d4",
      borderRadius: "0",
    },
  },
  {
    id: "sunset-warm",
    name: "Sunset Warm",
    description: "Warm, inviting theme with sunset colors",
    category: "creative",
    featured: false,
    colors: {
      primary: "#f97316",
      accent: "#db2777",
      background: "#fffbeb",
      foreground: "#1e293b",
      muted: "#94a3b8",
      border: "#fef3c7",
      linkBackground: "#fff7ed",
      linkForeground: "#9a3412",
      borderRadius: "0.5rem",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    description: "Classic black and white theme",
    category: "minimal",
    featured: false,
    colors: {
      primary: "#000000",
      accent: "#404040",
      background: "#ffffff",
      foreground: "#000000",
      muted: "#737373",
      border: "#e5e5e5",
      linkBackground: "#f5f5f5",
      linkForeground: "#000000",
      borderRadius: "0.25rem",
    },
  },
  {
    id: "midnight-purple",
    name: "Midnight Purple",
    description: "Deep purple theme with elegant accents",
    category: "dark",
    featured: false,
    colors: {
      primary: "#a855f7",
      accent: "#7e22ce",
      background: "#0f172a",
      foreground: "#f8fafc",
      muted: "#334155",
      border: "#1e293b",
      linkBackground: "#1e1b4b",
      linkForeground: "#e0e7ff",
      borderRadius: "0.5rem",
    },
  },
  {
    id: "pastel-dream",
    name: "Pastel Dream",
    description: "Soft, dreamy theme with pastel colors",
    category: "creative",
    featured: false,
    colors: {
      primary: "#c084fc",
      accent: "#94a3b8",
      background: "#f8fafc",
      foreground: "#1e293b",
      muted: "#94a3b8",
      border: "#e2e8f0",
      linkBackground: "#faf5ff",
      linkForeground: "#6b21a8",
      borderRadius: "1rem",
    },
  },
  {
    id: "winter-frost",
    name: "Winter Frost",
    description: "Cool, icy theme with blue tones",
    category: "seasonal",
    featured: false,
    colors: {
      primary: "#38bdf8",
      accent: "#0ea5e9",
      background: "#f0f9ff",
      foreground: "#0f172a",
      muted: "#94a3b8",
      border: "#e0f2fe",
      linkBackground: "#e0f2fe",
      linkForeground: "#0c4a6e",
      borderRadius: "0.5rem",
    },
  },
  {
    id: "autumn-leaves",
    name: "Autumn Leaves",
    description: "Warm autumn colors with earthy tones",
    category: "seasonal",
    featured: false,
    colors: {
      primary: "#d97706",
      accent: "#b45309",
      background: "#fffbeb",
      foreground: "#422006",
      muted: "#92400e",
      border: "#fef3c7",
      linkBackground: "#fef3c7",
      linkForeground: "#78350f",
      borderRadius: "0.375rem",
    },
  },
  {
    id: "spring-bloom",
    name: "Spring Bloom",
    description: "Fresh, light theme with floral accents",
    category: "seasonal",
    featured: false,
    colors: {
      primary: "#ec4899",
      accent: "#db2777",
      background: "#fdf2f8",
      foreground: "#831843",
      muted: "#be185d",
      border: "#fbcfe8",
      linkBackground: "#fbcfe8",
      linkForeground: "#9d174d",
      borderRadius: "0.75rem",
    },
  },
]
